//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VSMS_AmeeShreeEntities : DbContext
    {
        public VSMS_AmeeShreeEntities()
            : base("name=VSMS_AmeeShreeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Login_failed> M_Login_failed { get; set; }
        public virtual DbSet<M_Login> M_Login { get; set; }
        public virtual DbSet<M_Users> M_Users { get; set; }
        public virtual DbSet<M_Shift> M_Shift { get; set; }
        public virtual DbSet<M_Attendance> M_Attendance { get; set; }
        public virtual DbSet<M_ApplyLeave> M_ApplyLeave { get; set; }
        public virtual DbSet<M_LeaveType> M_LeaveType { get; set; }
    
        public virtual ObjectResult<sp_AddEmpGridData_Result> sp_AddEmpGridData(string fromDate, string toDate, string applicationStatus)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var applicationStatusParameter = applicationStatus != null ?
                new ObjectParameter("ApplicationStatus", applicationStatus) :
                new ObjectParameter("ApplicationStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AddEmpGridData_Result>("sp_AddEmpGridData", fromDateParameter, toDateParameter, applicationStatusParameter);
        }
    
        public virtual ObjectResult<sp_LeaveApprovalGridData_Result> sp_LeaveApprovalGridData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LeaveApprovalGridData_Result>("sp_LeaveApprovalGridData");
        }
    
        public virtual ObjectResult<sp_ApplyLeaveGridData_Result> sp_ApplyLeaveGridData(Nullable<int> month, Nullable<int> year, Nullable<int> userID)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApplyLeaveGridData_Result>("sp_ApplyLeaveGridData", monthParameter, yearParameter, userIDParameter);
        }
    }
}
