//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Attendance
    {
        public int AutoCode { get; set; }
        public Nullable<int> F_UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public string FirstHalf { get; set; }
        public string SecondHalf { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedIP { get; set; }
        public string InsertedBy { get; set; }
    
        public virtual M_Users M_Users { get; set; }
    }
}
