//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Login
    {
        public int LoginId { get; set; }
        public string EmailId { get; set; }
        public string SessionId { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public Nullable<System.DateTime> LoginOn { get; set; }
        public string logOn_IP { get; set; }
    }
}
