//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Shift
    {
        public int ShiftID { get; set; }
        public Nullable<decimal> Start_Time { get; set; }
        public Nullable<decimal> End_Time { get; set; }
        public Nullable<decimal> LunchStart_Time { get; set; }
        public Nullable<decimal> LunchEnd_Time { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedIP { get; set; }
    }
}
