//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Users()
        {
            this.M_Attendance = new HashSet<M_Attendance>();
            this.M_ApplyLeave = new HashSet<M_ApplyLeave>();
        }
    
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Password { get; set; }
        public string ResetPasswordToken { get; set; }
        public Nullable<System.DateTime> TokenExpiration { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string InsertedIP { get; set; }
        public string AorE { get; set; }
        public string isResignedYN { get; set; }
        public string Emergency_PhoneNo { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string WorkLocation { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Attendance> M_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ApplyLeave> M_ApplyLeave { get; set; }
    }
}
